/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Tela;

import Classes.Usuario;
import javax.swing.JOptionPane;

/** 
 *
 * @author Diorgenes
 */
public class TelaLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrameLogin
     */
    public TelaLogin() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelFavicon1 = new javax.swing.JLabel();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonMaximizar = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelNick = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jComboBoxCadastroMes = new javax.swing.JComboBox();
        jComboBoxCadastroAno = new javax.swing.JComboBox();
        jLabelSenha = new javax.swing.JLabel();
        jLabelConfirmaSenha = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jTextFieldCadastroNick = new javax.swing.JTextField();
        jTextFieldCadastroEmail = new javax.swing.JTextField();
        jPasswordCadastroSenha = new javax.swing.JPasswordField();
        jPasswordCadastroConfSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCadastroDia = new javax.swing.JComboBox();
        jTextFieldCadastroNome = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonEntrar = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();
        jLabelLoginSenha = new javax.swing.JLabel();
        jTextFieldLoginNick = new javax.swing.JTextField();
        jPasswordLoginSenha = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jButtonFace = new javax.swing.JButton();
        jButtonGoogle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFrameLogin");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabelFavicon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/favicon.gif"))); // NOI18N
        jLabelFavicon1.setToolTipText("");

        jButtonMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/min.png"))); // NOI18N
        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setBorderPainted(false);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMousePressed(evt);
            }
        });
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        jButtonMinimizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonMinimizarFocusLost(evt);
            }
        });

        jButtonMaximizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/max.png"))); // NOI18N
        jButtonMaximizar.setBorder(null);
        jButtonMaximizar.setBorderPainted(false);
        jButtonMaximizar.setContentAreaFilled(false);
        jButtonMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMaximizarMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMaximizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMaximizarMousePressed(evt);
            }
        });
        jButtonMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaximizarActionPerformed(evt);
            }
        });
        jButtonMaximizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonMaximizarFocusLost(evt);
            }
        });

        jButtonClose.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/close.png"))); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCloseMousePressed(evt);
            }
        });
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jButtonClose.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonCloseFocusLost(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar"));

        jLabelNick.setText("Nickname:");

        jLabelNome.setText("Nome Completo:");

        jLabelEmail.setText("Email:");

        jComboBoxCadastroMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxCadastroMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCadastroMesActionPerformed(evt);
            }
        });

        jComboBoxCadastroAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));
        jComboBoxCadastroAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCadastroAnoActionPerformed(evt);
            }
        });

        jLabelSenha.setText("Senha:");

        jLabelConfirmaSenha.setText("Confirmar Senha:");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jPasswordCadastroSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordCadastroSenhaActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Nascimento:");

        jComboBoxCadastroDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNick)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelEmail))
                    .addComponent(jLabelConfirmaSenha)
                    .addComponent(jLabelSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxCadastroDia, 0, 61, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCadastroMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCadastroAno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldCadastroNick)
                    .addComponent(jTextFieldCadastroEmail)
                    .addComponent(jPasswordCadastroConfSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordCadastroSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCadastroNome))
                .addContainerGap())
            .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick)
                    .addComponent(jTextFieldCadastroNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCadastroMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCadastroAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCadastroDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha)
                    .addComponent(jPasswordCadastroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmaSenha)
                    .addComponent(jPasswordCadastroConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jLabelLogin.setText("Nickname:");

        jLabelLoginSenha.setText("Senha:");

        jPasswordLoginSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordLoginSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogin)
                    .addComponent(jLabelLoginSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLoginNick)
                    .addComponent(jPasswordLoginSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
            .addComponent(jButtonEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextFieldLoginNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoginSenha)
                    .addComponent(jPasswordLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEntrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Redes Sociais"));

        jButtonFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/imagens/facebook-btn.png"))); // NOI18N
        jButtonFace.setText("Facebook");

        jButtonGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/imagens/google-btn.png"))); // NOI18N
        jButtonGoogle.setText("Google");
        jButtonGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoogleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonFace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGoogle)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MaiaChess v1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFavicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelFavicon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMinimizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMaximizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinimizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMinimizarMouseReleased

    private void jButtonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarMouseClicked

    private void jButtonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseEntered
        // TODO add your handling code here:
        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/min-hover.png"))); // NOI18N
    }//GEN-LAST:event_jButtonMinimizarMouseEntered

    private void jButtonMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseExited
        // TODO add your handling code here:
        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/min.png"))); // NOI18N
    }//GEN-LAST:event_jButtonMinimizarMouseExited

    private void jButtonMinimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMinimizarMousePressed

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonMinimizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonMinimizarFocusLost
        // TODO add your handling code here:
        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/min.png"))); // NOI18N
    }//GEN-LAST:event_jButtonMinimizarFocusLost

    private void jButtonMaximizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMaximizarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMaximizarMouseReleased

    private void jButtonMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMaximizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButtonMaximizarMouseClicked

    private void jButtonMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMaximizarMouseEntered
        // TODO add your handling code here:
        jButtonMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/max-hover.png"))); // NOI18N
    }//GEN-LAST:event_jButtonMaximizarMouseEntered

    private void jButtonMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMaximizarMouseExited
        // TODO add your handling code here:
        jButtonMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/max.png"))); // NOI18N
    }//GEN-LAST:event_jButtonMaximizarMouseExited

    private void jButtonMaximizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMaximizarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMaximizarMousePressed

    private void jButtonMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaximizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMaximizarActionPerformed

    private void jButtonMaximizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonMaximizarFocusLost
        // TODO add your handling code here:
        jButtonMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/max.png"))); // NOI18N
    }//GEN-LAST:event_jButtonMaximizarFocusLost

    private void jButtonCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseMouseReleased

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jButtonCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseEntered
        // TODO add your handling code here:
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/close-hover.png"))); // NOI18N
    }//GEN-LAST:event_jButtonCloseMouseEntered

    private void jButtonCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseExited
        // TODO add your handling code here:
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/close.png"))); // NOI18N
    }//GEN-LAST:event_jButtonCloseMouseExited

    private void jButtonCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseMousePressed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonCloseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonCloseFocusLost
        // TODO add your handling code here:
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buttons/close.png"))); // NOI18N
    }//GEN-LAST:event_jButtonCloseFocusLost

    private void jComboBoxCadastroMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCadastroMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCadastroMesActionPerformed

    private void jComboBoxCadastroAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCadastroAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCadastroAnoActionPerformed

    private void jButtonGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGoogleActionPerformed

    private void jPasswordCadastroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordCadastroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordCadastroSenhaActionPerformed

    private void jPasswordLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordLoginSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordLoginSenhaActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        String campos = "";
        if(jTextFieldCadastroNick.getText().equals(""))
        {
            campos+="-Nickname\n";
        }
        if(jTextFieldCadastroNome.getText().equals(""))
        {
            campos+="-Nome\n";
        }
        if(jTextFieldCadastroEmail.getText().equals(""))
        {
            campos+="-Email\n";
        }
        
        if(!campos.equals(""))
        {
            JOptionPane.showMessageDialog(this, "O(s) seguinte(s) são obrigatórios: \n\n"+campos);
        }
        else
        {
            if(!jPasswordCadastroSenha.getText().equals(jPasswordCadastroConfSenha.getText()) || jPasswordCadastroSenha.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "As senhas não estão coincidindo ou o campo não foi preenchido!");
            }
            else{
                Usuario u = null;
                
                if(u.Existe(jTextFieldCadastroNick.getText()))
                {
                    JOptionPane.showMessageDialog(this, "Nickname já em uso, por favor, escolha outro!");
                }
                else
                {
                    int mes = 0;
                    switch(jComboBoxCadastroMes.getSelectedItem().toString())
                    {
                        case "Janeiro":
                            mes = 1;
                            break;

                        case "Fevereiro":
                            mes = 2;
                            break;

                        case "Março":
                            mes = 3;
                            break;

                        case "Abril":
                            mes = 4;
                            break;

                        case "Maio":
                            mes = 5;
                            break;

                        case "Junho":
                            mes = 6;
                            break;

                        case "Julho":
                            mes = 7;
                            break;

                        case "Agosto":
                            mes = 8;
                            break;

                        case "Setembro":
                            mes = 9;
                            break;

                        case "Outubro":
                            mes = 10;
                            break;

                        case "Novembro":
                            mes = 11;
                            break;

                        case "Dezembro":
                            mes = 12;
                            break;

                    }

                    u = new Usuario(jTextFieldCadastroNick.getText(), jTextFieldCadastroEmail.getText(), 
                            jPasswordCadastroSenha.getText(), jTextFieldCadastroNome.getText(), 
                            Integer.parseInt(jComboBoxCadastroDia.getSelectedItem().toString()), 
                            mes, 
                            Integer.parseInt(jComboBoxCadastroAno.getSelectedItem().toString()));
                    
                    if(u.Salvar())
                    {
                        new Main(u).setVisible(true);
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Erro na inserção do Banco de Dados!");
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
        Usuario u = new Usuario(); 
        String nick = jTextFieldLoginNick.getText();
        if(u.Existe(nick))
        {
            u.setNick(nick);
            if(u.SelectById())
            {
                if(u.getSenha().equals(jPasswordLoginSenha.getText()))
                {
                    new Main(u).setVisible(true);
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos!");
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Erro no banco de dados!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos!");
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonFace;
    private javax.swing.JButton jButtonGoogle;
    private javax.swing.JButton jButtonMaximizar;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JComboBox jComboBoxCadastroAno;
    private javax.swing.JComboBox jComboBoxCadastroDia;
    private javax.swing.JComboBox jComboBoxCadastroMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelConfirmaSenha;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFavicon1;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoginSenha;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordCadastroConfSenha;
    private javax.swing.JPasswordField jPasswordCadastroSenha;
    private javax.swing.JPasswordField jPasswordLoginSenha;
    private javax.swing.JTextField jTextFieldCadastroEmail;
    private javax.swing.JTextField jTextFieldCadastroNick;
    private javax.swing.JTextField jTextFieldCadastroNome;
    private javax.swing.JTextField jTextFieldLoginNick;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
